// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/login.js";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/login.tsx";
import * as $5 from "./routes/logout.tsx";
import * as $6 from "./routes/signin.tsx";
import * as $7 from "./routes/signout.tsx";
import * as $8 from "./routes/who/[name].tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/login.js": $2,
    "./routes/index.tsx": $3,
    "./routes/login.tsx": $4,
    "./routes/logout.tsx": $5,
    "./routes/signin.tsx": $6,
    "./routes/signout.tsx": $7,
    "./routes/who/[name].tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
